// src/app/landing-page/register-page/register-page.tsx
import { IgrButton, IgrInput } from '@infragistics/igniteui-react';
import { useNavigate } from 'react-router-dom';
import { useState } from 'react';
import styles from './register-page.module.css';
import createClassTransformer from '../../style-utils';
import '/src/app/base-view-styles.css';

export default function RegisterPage() {
  const classes = createClassTransformer(styles);
  const navigate = useNavigate();
  const [value, setValue] = useState<string | undefined>();
  const [value1, setValue1] = useState<string | undefined>();
  const [value2, setValue2] = useState<string | undefined>();
  const [value3, setValue3] = useState<string | undefined>();

  return (
    <>
      <div className={classes("row-layout register-page-container")}>
        <div className={classes("row-layout registration-form-row-layout")}>
          <div className={classes("column-layout registration-form-column-layout")}>
            <div className={classes("column-layout registration-form-header")}>
              <h4 className={classes("content")}>
                <span>Create Account</span>
              </h4>
              <h6 className={classes("content")}>
                <span>Sign up to start your coffee journey</span>
              </h6>
            </div>
            <div className={classes("column-layout registration-form-fields")}>
              <IgrInput value={value} label="Full Name" placeholder="Enter your full name" required={true} outlined={true} onChange={(e) => setValue(e.detail)} className={classes("full-name-input")}>
                <p slot="value-missing">This field is required</p>
              </IgrInput>
              <IgrInput type="email" value={value1} label="Email address" placeholder="your.email@example.com" required={true} outlined={true} onChange={(e) => setValue1(e.detail)} className={classes("full-name-input")}>
                <p slot="value-missing">This field is required</p>
              </IgrInput>
              <IgrInput type="password" value={value2} label="Password" placeholder="Create a password" required={true} outlined={true} onChange={(e) => setValue2(e.detail)} className={classes("full-name-input")}>
                <p slot="value-missing">This field is required</p>
              </IgrInput>
              <IgrInput type="password" value={value3} label="Password" placeholder="Confirm your password" required={true} outlined={true} onChange={(e) => setValue3(e.detail)} className={classes("full-name-input")}>
                <p slot="value-missing">This field is required</p>
              </IgrInput>
              <IgrButton type="button" className={classes("create-account-button")}>
                <span>Create account</span>
              </IgrButton>
            </div>
            <div className={classes("row-layout login-prompt")}>
              <p className={classes("typography__body-2 content")}>
                <span>Already have an account?</span>
              </p>
              <a target="_blank" onClick={() => navigate(`/landing-page/login-page`)} className={classes("typography__body-2 sign-in-link")}>
                <span>Sign in</span>
              </a>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}

// src/app/landing-page/register-page/register-page.component.ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { IGX_INPUT_GROUP_DIRECTIVES, IgxButtonDirective } from '@infragistics/igniteui-angular';

@Component({
  selector: 'app-register-page',
  imports: [IGX_INPUT_GROUP_DIRECTIVES, IgxButtonDirective, FormsModule, RouterLink],
  templateUrl: './register-page.component.html',
  styleUrls: ['./register-page.component.scss']
})
export class RegisterPageComponent {
  public value?: string;
  public value1?: string;
  public value2?: string;
  public value3?: string;
}

<div class="row-layout registration-form-row-layout">
  <div class="column-layout registration-form-column-layout">
    <div class="column-layout registration-form-header">
      <h4 class="content">
        Create Account
      </h4>
      <h6 class="content">
        Sign up to start your coffee journey
      </h6>
    </div>
    <div class="column-layout registration-form-fields">
      <igx-input-group type="border" class="full-name-input">
        <input type="text" [(ngModel)]="value" placeholder="Enter your full name" required="true" igxInput #igxInput />
        <label igxLabel>Full Name</label>
        @if (igxInput.validity.valueMissing) {
          <igx-hint>This field is required</igx-hint>
        }
      </igx-input-group>
      <igx-input-group type="border" class="full-name-input">
        <input type="email" [(ngModel)]="value1" placeholder="your.email@example.com" required="true" igxInput #igxInput1 />
        <label igxLabel>Email address</label>
        @if (igxInput1.validity.valueMissing) {
          <igx-hint>This field is required</igx-hint>
        }
      </igx-input-group>
      <igx-input-group type="border" class="full-name-input">
        <input type="password" [(ngModel)]="value2" placeholder="Create a password" required="true" igxInput #igxInput2 />
        <label igxLabel>Password</label>
        @if (igxInput2.validity.valueMissing) {
          <igx-hint>This field is required</igx-hint>
        }
      </igx-input-group>
      <igx-input-group type="border" class="full-name-input">
        <input type="password" [(ngModel)]="value3" placeholder="Confirm your password" required="true" igxInput #igxInput3 />
        <label igxLabel>Password</label>
        @if (igxInput3.validity.valueMissing) {
          <igx-hint>This field is required</igx-hint>
        }
      </igx-input-group>
      <button igxButton="contained" type="button" class="create-account-button">
        Create account
      </button>
    </div>
    <div class="row-layout login-prompt">
      <p class="ig-typography__body-2 content">
        Already have an account?
      </p>
      <a target="_blank" [routerLink]="[`/landing-page/login-page`]" class="ig-typography__body-2 sign-in-link">
        Sign in
      </a>
    </div>
  </div>
</div>
