// src/app/user-dashboard/user-dashboard.tsx
import { IgrAvatar, IgrCalendar, IgrCard, IgrCardContent, IgrCardHeader, IgrList, IgrListItem } from '@infragistics/igniteui-react';
import { IgrPieChart, IgrPieChartModule } from '@infragistics/igniteui-react-charts';
import { useState } from 'react';
import { useGetCoffeeFlavorProfiles } from '../hooks/coffee-flavor-preferences-hooks';
import styles from './user-dashboard.module.css';
import createClassTransformer from '../style-utils';
import '/src/app/base-view-styles.css';

IgrPieChartModule.register();

export default function UserDashboard() {
  const classes = createClassTransformer(styles);
  const date = new Date('10/26/2024 00:00:00');
  const [recentOrdersListSelectedItem, setRecentOrdersListSelectedItem] = useState<string | undefined>();
  const [subscriptionInfoListSelectedItem, setSubscriptionInfoListSelectedItem] = useState<string | undefined>();
  const { coffeeFlavorPreferencesCoffeeFlavorProfiles } = useGetCoffeeFlavorProfiles();

  return (
    <>
      <div className={classes("column-layout user-dashboard-container")}>
        <div className={classes("column-layout dashboard-content")}>
          <div className={classes("column-layout dashboard-header")}>
            <h4 className={classes("content")}>
              <span>My Coffee Dashboard</span>
            </h4>
            <p className={classes("typography__body-1 content")}>
              <span>Manage your subscription, view shipments, and explore your flavor profile.</span>
            </p>
          </div>
          <div className={classes("row-layout dashboard-metrics")}>
            <IgrCard className={classes("next-shipment-card")}>
              <IgrCardHeader>
                <div slot="thumbnail">
                  <IgrAvatar shape="circle" className={classes("next-shipment-icon")}>
                    <span className={classes("material-icons icon")}>
                      <span>local_shipping</span>
                    </span>
                  </IgrAvatar>
                </div>
                <h3 slot="title">
                  <span>Next Shipment</span>
                </h3>
                <h5 slot="subtitle">
                  <span></span>
                </h5>
              </IgrCardHeader>
              <IgrCardContent className={classes("body-content")}>
                <div className={classes("column-layout next-shipment-content")}>
                  <h3 className={classes("content")}>
                    <span>Oct 26, 2024</span>
                  </h3>
                  <div className={classes("row-layout next-shipment-details")}>
                    <p className={classes("typography__subtitle-2 shipment-status")}>
                      <span>On Schedule</span>
                    </p>
                    <p className={classes("typography__body-2 content")}>
                      <span>Your next delivery is almost here!</span>
                    </p>
                  </div>
                </div>
              </IgrCardContent>
            </IgrCard>
            <IgrCard className={classes("next-shipment-card")}>
              <IgrCardHeader>
                <div slot="thumbnail">
                  <IgrAvatar shape="circle" className={classes("next-shipment-icon_1")}>
                    <span className={classes("material-icons icon_1")}>
                      <span>event</span>
                    </span>
                  </IgrAvatar>
                </div>
                <h3 slot="title">
                  <span>Delivery Calendar</span>
                </h3>
                <h5 slot="subtitle">
                  <span></span>
                </h5>
              </IgrCardHeader>
              <IgrCardContent className={classes("body-content")}>
                <div className={classes("column-layout next-shipment-content")}>
                  <IgrCalendar hideHeader={true} headerOrientation="horizontal" value={date} className={classes("delivery-calendar")}></IgrCalendar>
                </div>
              </IgrCardContent>
            </IgrCard>
            <IgrCard className={classes("next-shipment-card")}>
              <IgrCardHeader>
                <div slot="thumbnail">
                  <IgrAvatar shape="circle" className={classes("next-shipment-icon_2")}>
                    <span className={classes("material-icons icon_2")}>
                      <span>water_drop</span>
                    </span>
                  </IgrAvatar>
                </div>
                <h3 slot="title">
                  <span>Coffee Flavor Profile</span>
                </h3>
                <h5 slot="subtitle">
                  <span></span>
                </h5>
              </IgrCardHeader>
              <IgrCardContent className={classes("body-content")}>
                <div className={classes("column-layout next-shipment-content")}>
                  <div className={classes("group")}>
                    <IgrPieChart dataSource={coffeeFlavorPreferencesCoffeeFlavorProfiles} labelMemberPath valueMemberPath></IgrPieChart>
                  </div>
                </div>
              </IgrCardContent>
            </IgrCard>
          </div>
          <div className={classes("row-layout dashboard-statistics")}>
            <div className={classes("column-layout recent-orders-section")}>
              <div className={classes("column-layout dashboard-header")}>
                <h5 className={classes("content")}>
                  <span>Recent Orders</span>
                </h5>
                <p className={classes("typography__body-2 content")}>
                  <span>Your latest coffee deliveries</span>
                </p>
              </div>
              <IgrList className={classes("recent-orders-list")}>
                <div style={{ display: 'contents' }} onClick={() => setRecentOrdersListSelectedItem('0')}>
                  <IgrListItem selected={recentOrdersListSelectedItem != null && recentOrdersListSelectedItem === '0'}>
                    <div slot="start">
                      <IgrAvatar shape="circle" className={classes("order-1-avatar order-1-avatar_1")}>
                        <span className={classes("material-icons icon_3")}>
                          <span>coffee</span>
                        </span>
                      </IgrAvatar>
                    </div>
                    <div slot="title">Ethiopian Yirgacheffe</div>
                    <div slot="subtitle">Delivered Oct 10, 2024</div>
                  </IgrListItem>
                </div>
                <div style={{ display: 'contents' }} onClick={() => setRecentOrdersListSelectedItem('1')}>
                  <IgrListItem selected={recentOrdersListSelectedItem != null && recentOrdersListSelectedItem === '1'}>
                    <div slot="start">
                      <IgrAvatar shape="circle" className={classes("order-1-avatar order-1-avatar_2")}>
                        <span className={classes("material-icons icon_3")}>
                          <span>coffee</span>
                        </span>
                      </IgrAvatar>
                    </div>
                    <div slot="title">Brazilian Santos</div>
                    <div slot="subtitle">Delivered Sep 10, 2024</div>
                  </IgrListItem>
                </div>
              </IgrList>
            </div>
            <div className={classes("column-layout recent-orders-section")}>
              <div className={classes("column-layout dashboard-header")}>
                <h5 className={classes("content")}>
                  <span>Subscription Details</span>
                </h5>
                <p className={classes("typography__body-2 content")}>
                  <span>Your current plan and next billing date</span>
                </p>
              </div>
              <IgrList className={classes("recent-orders-list")}>
                <div style={{ display: 'contents' }} onClick={() => setSubscriptionInfoListSelectedItem('0')}>
                  <IgrListItem selected={subscriptionInfoListSelectedItem != null && subscriptionInfoListSelectedItem === '0'}>
                    <div slot="start">
                      <IgrAvatar shape="circle" className={classes("order-1-avatar order-1-avatar_3")}>
                        <span className={classes("material-icons icon_3")}>
                          <span>military_tech</span>
                        </span>
                      </IgrAvatar>
                    </div>
                    <div slot="title">Current Plan</div>
                    <div slot="subtitle">Enthusiast Brew</div>
                  </IgrListItem>
                </div>
                <div style={{ display: 'contents' }} onClick={() => setSubscriptionInfoListSelectedItem('1')}>
                  <IgrListItem selected={subscriptionInfoListSelectedItem != null && subscriptionInfoListSelectedItem === '1'}>
                    <div slot="start">
                      <IgrAvatar shape="circle" className={classes("order-1-avatar order-1-avatar_4")}>
                        <span className={classes("material-icons icon_3")}>
                          <span>payment</span>
                        </span>
                      </IgrAvatar>
                    </div>
                    <div slot="title">Next Billing Date</div>
                    <div slot="subtitle">Oct 26, 2024</div>
                  </IgrListItem>
                </div>
              </IgrList>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}

// src/app/user-dashboard/user-dashboard.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { IGX_CALENDAR_DIRECTIVES, IGX_CARD_DIRECTIVES, IGX_LIST_DIRECTIVES, IgxAvatarComponent, IgxIconComponent } from '@infragistics/igniteui-angular';
import { IgxPieChartModule } from 'igniteui-angular-charts';
import { Subject, takeUntil } from 'rxjs';
import { CoffeeFlavorProfilesType } from '../models/coffee-flavor-preferences/coffee-flavor-profiles-type';
import { CoffeeFlavorPreferencesService } from '../services/coffee-flavor-preferences.service';

@Component({
  selector: 'app-user-dashboard',
  imports: [IGX_CALENDAR_DIRECTIVES, IGX_CARD_DIRECTIVES, IGX_LIST_DIRECTIVES, IgxPieChartModule, IgxAvatarComponent, IgxIconComponent],
  templateUrl: './user-dashboard.component.html',
  styleUrls: ['./user-dashboard.component.scss']
})
export class UserDashboardComponent implements OnInit, OnDestroy {
  private destroy$: Subject<void> = new Subject<void>();
  public recentOrdersListSelectedItem?: string;
  public subscriptionInfoListSelectedItem?: string;
  public date: Date = new Date('10/26/2024 00:00:00');
  public coffeeFlavorPreferencesCoffeeFlavorProfiles: CoffeeFlavorProfilesType[] = [];

  constructor(
    public coffeeFlavorPreferencesService: CoffeeFlavorPreferencesService,
  ) {}


  ngOnInit() {
    this.coffeeFlavorPreferencesService.getCoffeeFlavorProfiles().pipe(takeUntil(this.destroy$)).subscribe(
      data => this.coffeeFlavorPreferencesCoffeeFlavorProfiles = data
    );
  }

  ngOnDestroy() {
    this.destroy$.next();
    this.destroy$.complete();
  }
}

<div class="column-layout dashboard-content">
  <div class="column-layout dashboard-header">
    <h4 class="content">
      My Coffee Dashboard
    </h4>
    <p class="content">
      Manage your subscription, view shipments, and explore your flavor profile.
    </p>
  </div>
  <div class="row-layout dashboard-metrics">
    <igx-card class="next-shipment-card">
      <igx-card-header>
        <div igxCardThumbnail>
          <igx-avatar shape="circle" class="next-shipment-icon next-shipment-icon_1">
            <igx-icon class="icon">
              local_shipping
            </igx-icon>
          </igx-avatar>
        </div>
        <h3 igxCardHeaderTitle>
          Next Shipment
        </h3>
        <h5 igxCardHeaderSubtitle>
      </h5>
      </igx-card-header>
      <igx-card-content class="body-content">
        <div class="column-layout next-shipment-content">
          <h3 class="content">
            Oct 26, 2024
          </h3>
          <div class="row-layout next-shipment-details">
            <p class="ig-typography__subtitle-2 shipment-status">
              On Schedule
            </p>
            <p class="ig-typography__body-2 content">
              Your next delivery is almost here!
            </p>
          </div>
        </div>
      </igx-card-content>
    </igx-card>
    <igx-card class="next-shipment-card">
      <igx-card-header>
        <div igxCardThumbnail>
          <igx-avatar shape="circle" class="delivery-calendar-icon delivery-calendar-icon_1">
            <igx-icon class="icon_1">
              event
            </igx-icon>
          </igx-avatar>
        </div>
        <h3 igxCardHeaderTitle>
          Delivery Calendar
        </h3>
        <h5 igxCardHeaderSubtitle>
      </h5>
      </igx-card-header>
      <igx-card-content class="body-content">
        <div class="column-layout next-shipment-content">
          <igx-calendar [hasHeader]="false" [value]="date" class="delivery-calendar"></igx-calendar>
        </div>
      </igx-card-content>
    </igx-card>
    <igx-card class="next-shipment-card">
      <igx-card-header>
        <div igxCardThumbnail>
          <igx-avatar shape="circle" class="flavor-profile-icon flavor-profile-icon_1">
            <igx-icon class="icon_2">
              water_drop
            </igx-icon>
          </igx-avatar>
        </div>
        <h3 igxCardHeaderTitle>
          Coffee Flavor Profile
        </h3>
        <h5 igxCardHeaderSubtitle>
      </h5>
      </igx-card-header>
      <igx-card-content class="body-content">
        <div class="column-layout next-shipment-content">
          <igx-pie-chart [dataSource]="coffeeFlavorPreferencesCoffeeFlavorProfiles" labelMemberPath="" valueMemberPath="" class="flavor-profile-chart"></igx-pie-chart>
        </div>
      </igx-card-content>
    </igx-card>
  </div>
  <div class="row-layout dashboard-statistics">
    <div class="column-layout recent-orders-section">
      <div class="column-layout dashboard-header">
        <h5 class="content">
          Recent Orders
        </h5>
        <p class="ig-typography__body-2 content">
          Your latest coffee deliveries
        </p>
      </div>
      <igx-list class="recent-orders-list">
        <igx-list-item [selected]="this.recentOrdersListSelectedItem != null && this.recentOrdersListSelectedItem === '0'" (click)="recentOrdersListSelectedItem = '0'">
          <span igxListThumbnail>
            <igx-avatar shape="circle" class="order-1-avatar order-1-avatar_1">
              <igx-icon class="icon_3">
                coffee
              </igx-icon>
            </igx-avatar>
          </span>
          <span igxListLineTitle>Ethiopian Yirgacheffe</span>
          <span igxListLineSubTitle>Delivered Oct 10, 2024</span>
        </igx-list-item>
        <igx-list-item [selected]="this.recentOrdersListSelectedItem != null && this.recentOrdersListSelectedItem === '1'" (click)="recentOrdersListSelectedItem = '1'">
          <span igxListThumbnail>
            <igx-avatar shape="circle" class="order-1-avatar order-1-avatar_2">
              <igx-icon class="icon_3">
                coffee
              </igx-icon>
            </igx-avatar>
          </span>
          <span igxListLineTitle>Brazilian Santos</span>
          <span igxListLineSubTitle>Delivered Sep 10, 2024</span>
        </igx-list-item>
      </igx-list>
    </div>
    <div class="column-layout recent-orders-section">
      <div class="column-layout dashboard-header">
        <h5 class="content">
          Subscription Details
        </h5>
        <p class="ig-typography__body-2 content">
          Your current plan and next billing date
        </p>
      </div>
      <igx-list class="recent-orders-list">
        <igx-list-item [selected]="this.subscriptionInfoListSelectedItem != null && this.subscriptionInfoListSelectedItem === '0'" (click)="subscriptionInfoListSelectedItem = '0'">
          <span igxListThumbnail>
            <igx-avatar shape="circle" class="order-1-avatar order-1-avatar_3">
              <igx-icon class="icon_3">
                military_tech
              </igx-icon>
            </igx-avatar>
          </span>
          <span igxListLineTitle>Current Plan</span>
          <span igxListLineSubTitle>Enthusiast Brew</span>
        </igx-list-item>
        <igx-list-item [selected]="this.subscriptionInfoListSelectedItem != null && this.subscriptionInfoListSelectedItem === '1'" (click)="subscriptionInfoListSelectedItem = '1'">
          <span igxListThumbnail>
            <igx-avatar shape="circle" class="order-1-avatar order-1-avatar_4">
              <igx-icon class="icon_3">
                payment
              </igx-icon>
            </igx-avatar>
          </span>
          <span igxListLineTitle>Next Billing Date</span>
          <span igxListLineSubTitle>Oct 26, 2024</span>
        </igx-list-item>
      </igx-list>
    </div>
  </div>
</div>
