// src/app/landing-page/login-page/login-page.tsx
import { IgrButton, IgrCheckbox, IgrInput } from '@infragistics/igniteui-react';
import { useNavigate } from 'react-router-dom';
import { useState } from 'react';
import styles from './login-page.module.css';
import createClassTransformer from '../../style-utils';
import '/src/app/base-view-styles.css';

export default function LoginPage() {
  const classes = createClassTransformer(styles);
  const navigate = useNavigate();
  const [value, setValue] = useState<string | undefined>();
  const [value1, setValue1] = useState<string | undefined>();
  const [checked, setChecked] = useState<boolean>(false);

  return (
    <>
      <div className={classes("row-layout login-page-container")}>
        <div className={classes("row-layout login-form-row-layout")}>
          <div className={classes("column-layout login-form-column-layout")}>
            <h4 className={classes("content")}>
              <span>Login</span>
            </h4>
            <div className={classes("column-layout login-form-fields")}>
              <IgrInput type="email" value={value} label="Email address" required={true} outlined={true} onChange={(e) => setValue(e.detail)} className={classes("login-email-input")}>
                <p slot="value-missing">This field is required</p>
              </IgrInput>
              <IgrInput type="password" value={value1} label="Password" required={true} outlined={true} onChange={(e) => setValue1(e.detail)} className={classes("login-email-input")}>
                <p slot="value-missing">This field is required</p>
              </IgrInput>
              <div className={classes("row-layout remember-me-forgot-pass")}>
                <IgrCheckbox labelPosition="after" checked={checked} onChange={(e) => setChecked(!!e.detail.checked)} className={classes("remember-me-checkbox")}>
                  <span>Remember me</span>
                </IgrCheckbox>
                <a target="_blank" className={classes("typography__body-2 forgot-password-link")}>
                  <span>Forgot your password?</span>
                </a>
              </div>
              <IgrButton type="button" className={classes("sign-in-button")}>
                <span>Sign in</span>
              </IgrButton>
            </div>
            <div className={classes("row-layout create-account-prompt")}>
              <p className={classes("typography__body-2 content")}>
                <span>Don't have an account?</span>
              </p>
              <a target="_blank" onClick={() => navigate(`/landing-page/register-page`)} className={classes("typography__body-2 create-account-link")}>
                <span>Create new account</span>
              </a>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}

// src/app/landing-page/login-page/login-page.component.ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { IGX_INPUT_GROUP_DIRECTIVES, IgxButtonDirective, IgxCheckboxComponent } from '@infragistics/igniteui-angular';

@Component({
  selector: 'app-login-page',
  imports: [IGX_INPUT_GROUP_DIRECTIVES, IgxCheckboxComponent, IgxButtonDirective, FormsModule, RouterLink],
  templateUrl: './login-page.component.html',
  styleUrls: ['./login-page.component.scss']
})
export class LoginPageComponent {
  public value?: string;
  public value1?: string;
  public checked = false;
}

<div class="row-layout login-form-row-layout">
  <div class="column-layout login-form-column-layout">
    <h4 class="content">
      Login
    </h4>
    <div class="column-layout login-form-fields">
      <igx-input-group type="border" class="login-email-input">
        <input type="email" [(ngModel)]="value" required="true" igxInput #igxInput />
        <label igxLabel>Email address</label>
        @if (igxInput.validity.valueMissing) {
          <igx-hint>This field is required</igx-hint>
        }
      </igx-input-group>
      <igx-input-group type="border" class="login-email-input">
        <input type="password" [(ngModel)]="value1" required="true" igxInput #igxInput1 />
        <label igxLabel>Password</label>
        @if (igxInput1.validity.valueMissing) {
          <igx-hint>This field is required</igx-hint>
        }
      </igx-input-group>
      <div class="row-layout remember-me-forgot-pass">
        <igx-checkbox labelPosition="after" [(ngModel)]="checked" class="remember-me-checkbox">
          Remember me
        </igx-checkbox>
        <a target="_blank" class="ig-typography__body-2 forgot-password-link">
          Forgot your password?
        </a>
      </div>
      <button igxButton="contained" type="button" class="sign-in-button">
        Sign in
      </button>
    </div>
    <div class="row-layout create-account-prompt">
      <p class="ig-typography__body-2 content">
        Don't have an account?
      </p>
      <a target="_blank" [routerLink]="[`/landing-page/register-page`]" class="ig-typography__body-2 create-account-link">
        Create new account
      </a>
    </div>
  </div>
</div>
